// <auto-generated />
namespace StoreCar.Migrations.ContextB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Producttablenew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Producttablenew));
        
        string IMigrationMetadata.Id
        {
            get { return "201908131139342_Product table new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
